version: '3'

services:
  haproxy:
    # build: ./haproxy
    image: haproxy:1.6.14-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
     - '8080:8080'

  nginx:
    image: nginx:1.14.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # ports:
    #   - '8181:8181'

  socket_server:
    build: ./socket_server/.
